using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
 
namespace PostroenieMinOstovnogoDereva
{
    class Program
    {
        static void Main(string[] args)
        {
            int n; // количество вершин минимального остовного дерева
            int b1,b2,b3,b4,b5,b6,b7,b8,b9,b10,b11,b12,b13,b14,b15,b16,b17,b18,b19,b20,b21,b22,b23,b24,b25,b26,b27,b28,b29,b30,b31,b32,b33,b34,b35,b36,b37,b38,b39,b40,b41,b42,b43,b44,b45,b46,b47,b48,b49,b50,b51,b52,b53,b54,b55,b56,b57,b58,b59,b60,b61,b62,b63,b64,b65,b66,b67,b68,b69,b70,b71,b72,b73,b74,b75,b76,b77,b78,b79,b80,b81,b82,b83,b84,b85,b86,b87,b88,b89,b90,b91,b92,b93,b94,b95,b96,b97,b98,b99,b100;
            float[,] a, a1; // матрицы весов графа и его остова
            Console.WriteLine("Введите количество вершин графа");
            n = int.Parse(Console.ReadLine());
            float[] used = new float[n]; // Массив использованных вершин
            short i, j;
            int count = 0; // фиксированная первая вершина 
            float s1 = 0; // вес остова
            a = new float[n, n];
            a1 = new float[n, n];

// метод математических матриц для разного количества вершин
            if (n == 2)
            {
                Console.WriteLine("Введите число соответствующее первому элементу столбца, первому элементу строки");
                b1 = int.Parse(Console.ReadLine());
                a[0, 0] = b1;
                Console.WriteLine("Введите число соответствующее второму элементу столбца, первому элементу строки");
                b2 = int.Parse(Console.ReadLine());
                a[0, 1] = b2;
                Console.WriteLine("Введите число соответствующее первому элементу столбца, второму элементу строки");
                b5 = int.Parse(Console.ReadLine());
                a[1, 0] = b5;
                Console.WriteLine("Введите число соответствующее второму элементу столбца, второму элементу строки");
                b6 = int.Parse(Console.ReadLine());
                a[1, 1] = b6;
            }

            if (n == 3)
            {
                Console.WriteLine("Введите число соответствующее первому элементу столбца, первому элементу строки");
                b1 = int.Parse(Console.ReadLine());
                a[0, 0] = b1;
                Console.WriteLine("Введите число соответствующее второму элементу столбца, первому элементу строки");
                b2 = int.Parse(Console.ReadLine());
                a[0, 1] = b2;
                Console.WriteLine("Введите число соответствующее третьему элементу столбца, первому элементу строки");
                b3 = int.Parse(Console.ReadLine());
                a[0, 2] = b3;
                Console.WriteLine("Введите число соответствующее первому элементу столбца, второму элементу строки");
                b5 = int.Parse(Console.ReadLine());
                a[1, 0] = b5;
                Console.WriteLine("Введите число соответствующее второму элементу столбца, второму элементу строки");
                b6 = int.Parse(Console.ReadLine());
                a[1, 1] = b6;
                Console.WriteLine("Введите число соответствующее третьему элементу столбца, второму элементу строки");
                b7 = int.Parse(Console.ReadLine());
                a[1, 2] = b7;
                Console.WriteLine("Введите число соответствующее первому элементу столбца, третьему элементу строки");
                b9 = int.Parse(Console.ReadLine());
                a[2, 0] = b9;
                Console.WriteLine("Введите число соответствующее второму элементу столбца, третьему элементу строки");
                b10 = int.Parse(Console.ReadLine());
                a[2, 1] = b10;
                Console.WriteLine("Введите число соответствующее третьему элементу столбца, третьему элементу строки");
                b11 = int.Parse(Console.ReadLine());
                a[2, 2] = b11;
            }
            if (n == 4)
            {
                Console.WriteLine("Введите число соответствующее первому элементу столбца, первому элементу строки");
                b1 = int.Parse(Console.ReadLine());
                a[0, 0] = b1;
                Console.WriteLine("Введите число соответствующее второму элементу столбца, первому элементу строки");
                b2 = int.Parse(Console.ReadLine());
                a[0, 1] = b2;
                Console.WriteLine("Введите число соответствующее третьему элементу столбца, первому элементу строки");
                b3 = int.Parse(Console.ReadLine());
                a[0, 2] = b3;
                Console.WriteLine("Введите число соответствующее четвертому элементу столбца, первому элементу строки");
                b4 = int.Parse(Console.ReadLine());
                a[0, 3] = b4;
                Console.WriteLine("Введите число соответствующее первому элементу столбца, второму элементу строки");
                b5 = int.Parse(Console.ReadLine());
                a[1, 0] = b5;
                Console.WriteLine("Введите число соответствующее второму элементу столбца, второму элементу строки");
                b6 = int.Parse(Console.ReadLine());
                a[1, 1] = b6;
                Console.WriteLine("Введите число соответствующее третьему элементу столбца, второму элементу строки");
                b7 = int.Parse(Console.ReadLine());
                a[1, 2] = b7;
                Console.WriteLine("Введите число соответствующее четвертому элементу столбца, второму элементу строки");
                b8 = int.Parse(Console.ReadLine());
                a[1, 3] = b8;
                Console.WriteLine("Введите число соответствующее первому элементу столбца, третьему элементу строки");
                b9 = int.Parse(Console.ReadLine());
                a[2, 0] = b9;
                Console.WriteLine("Введите число соответствующее второму элементу столбца, третьему элементу строки");
                b10 = int.Parse(Console.ReadLine());
                a[2, 1] = b10;
                Console.WriteLine("Введите число соответствующее третьему элементу столбца, третьему элементу строки");
                b11 = int.Parse(Console.ReadLine());
                a[2, 2] = b11;
                Console.WriteLine("Введите число соответствующее четвертому элементу столбца, третьему элементу строки");
                b12 = int.Parse(Console.ReadLine());
                a[2, 3] = b12;
                Console.WriteLine("Введите число соответствующее первому элементу столбца, четвертому элементу строки");
                b13 = int.Parse(Console.ReadLine());
                a[3, 0] = b13;
                Console.WriteLine("Введите число соответствующее второму элементу столбца, четвертому элементу строки");
                b14 = int.Parse(Console.ReadLine());
                a[3, 1] = b14;
                Console.WriteLine("Введите число соответствующее третьему элементу столбца, четвертому элементу строки");
                b15 = int.Parse(Console.ReadLine());
                a[3, 2] = b15;
                Console.WriteLine("Введите число соответствующее четвертому элементу столбца, четвертому элементу строки");
                b16 = int.Parse(Console.ReadLine());
                a[3, 3] = b16;
            }
            if (n == 5)
            {
                Console.WriteLine("Введите число соответствующее первому элементу столбца, первому элементу строки");
                b1 = int.Parse(Console.ReadLine());
                a[0, 0] = b1;
                Console.WriteLine("Введите число соответствующее второму элементу столбца, первому элементу строки");
                b2 = int.Parse(Console.ReadLine());
                a[0, 1] = b2;
                Console.WriteLine("Введите число соответствующее третьему элементу столбца, первому элементу строки");
                b3 = int.Parse(Console.ReadLine());
                a[0, 2] = b3;
                Console.WriteLine("Введите число соответствующее четвертому элементу столбца, первому элементу строки");
                b4 = int.Parse(Console.ReadLine());
                a[0, 3] = b4;
                Console.WriteLine("Введите число соответствующее пятому элементу столбца, первому элементу строки");
                b17 = int.Parse(Console.ReadLine());
                a[0, 4] = b17;
                Console.WriteLine("Введите число соответствующее первому элементу столбца, второму элементу строки");
                b5 = int.Parse(Console.ReadLine());
                a[1, 0] = b5;
                Console.WriteLine("Введите число соответствующее второму элементу столбца, второму элементу строки");
                b6 = int.Parse(Console.ReadLine());
                a[1, 1] = b6;
                Console.WriteLine("Введите число соответствующее третьему элементу столбца, второму элементу строки");
                b7 = int.Parse(Console.ReadLine());
                a[1, 2] = b7;
                Console.WriteLine("Введите число соответствующее четвертому элементу столбца, второму элементу строки");
                b8 = int.Parse(Console.ReadLine());
                a[1, 3] = b8;
                Console.WriteLine("Введите число соответствующее пятому элементу столбца, второму элементу строки");
                b18 = int.Parse(Console.ReadLine());
                a[1, 4] = b18;
                Console.WriteLine("Введите число соответствующее первому элементу столбца, третьему элементу строки");
                b9 = int.Parse(Console.ReadLine());
                a[2, 0] = b9;
                Console.WriteLine("Введите число соответствующее второму элементу столбца, третьему элементу строки");
                b10 = int.Parse(Console.ReadLine());
                a[2, 1] = b10;
                Console.WriteLine("Введите число соответствующее третьему элементу столбца, третьему элементу строки");
                b11 = int.Parse(Console.ReadLine());
                a[2, 2] = b11;
                Console.WriteLine("Введите число соответствующее четвертому элементу столбца, третьему элементу строки");
                b12 = int.Parse(Console.ReadLine());
                a[2, 3] = b12;
                Console.WriteLine("Введите число соответствующее пятому элементу столбца, третьему элементу строки");
                b19 = int.Parse(Console.ReadLine());
                a[2, 4] = b19;
                Console.WriteLine("Введите число соответствующее первому элементу столбца, четвертому элементу строки");
                b13 = int.Parse(Console.ReadLine());
                a[3, 0] = b13;
                Console.WriteLine("Введите число соответствующее второму элементу столбца, четвертому элементу строки");
                b14 = int.Parse(Console.ReadLine());
                a[3, 1] = b14;
                Console.WriteLine("Введите число соответствующее третьему элементу столбца, четвертому элементу строки");
                b15 = int.Parse(Console.ReadLine());
                a[3, 2] = b15;
                Console.WriteLine("Введите число соответствующее четвертому элементу столбца, четвертому элементу строки");
                b16 = int.Parse(Console.ReadLine());
                a[3, 3] = b16;
                Console.WriteLine("Введите число соответствующее пятому элементу столбца, четвертому элементу строки");
                b20 = int.Parse(Console.ReadLine());
                a[3, 4] = b20;
                Console.WriteLine("Введите число соответствующее первому элементу столбца, пятому элементу строки");
                b21 = int.Parse(Console.ReadLine());
                a[4, 0] = b21;
                Console.WriteLine("Введите число соответствующее второму элементу столбца, пятому элементу строки");
                b22 = int.Parse(Console.ReadLine());
                a[4, 1] = b22;
                Console.WriteLine("Введите число соответствующее третьему элементу столбца, пятому элементу строки");
                b23 = int.Parse(Console.ReadLine());
                a[4, 2] = b23;
                Console.WriteLine("Введите число соответствующее четвертому элементу столбца, пятому элементу строки");
                b24 = int.Parse(Console.ReadLine());
                a[4, 3] = b24;
                Console.WriteLine("Введите число соответствующее пятому элементу столбца, пятому элементу строки");
                b25 = int.Parse(Console.ReadLine());
                a[4, 4] = b25;
            }
            if (n == 6)
            {
                Console.WriteLine("Введите число соответствующее первому элементу столбца, первому элементу строки");
                b1 = int.Parse(Console.ReadLine());
                a[0, 0] = b1;
                Console.WriteLine("Введите число соответствующее второму элементу столбца, первому элементу строки");
                b2 = int.Parse(Console.ReadLine());
                a[0, 1] = b2;
                Console.WriteLine("Введите число соответствующее третьему элементу столбца, первому элементу строки");
                b3 = int.Parse(Console.ReadLine());
                a[0, 2] = b3;
                Console.WriteLine("Введите число соответствующее четвертому элементу столбца, первому элементу строки");
                b4 = int.Parse(Console.ReadLine());
                a[0, 3] = b4;
                Console.WriteLine("Введите число соответствующее пятому элементу столбца, первому элементу строки");
                b17 = int.Parse(Console.ReadLine());
                a[0, 4] = b17;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, первому элементу строки");
                b26 = int.Parse(Console.ReadLine());
                a[0, 5] = b26;
                Console.WriteLine("Введите число соответствующее первому элементу столбца, второму элементу строки");
                b5 = int.Parse(Console.ReadLine());
                a[1, 0] = b5;
                Console.WriteLine("Введите число соответствующее второму элементу столбца, второму элементу строки");
                b6 = int.Parse(Console.ReadLine());
                a[1, 1] = b6;
                Console.WriteLine("Введите число соответствующее третьему элементу столбца, второму элементу строки");
                b7 = int.Parse(Console.ReadLine());
                a[1, 2] = b7;
                Console.WriteLine("Введите число соответствующее четвертому элементу столбца, второму элементу строки");
                b8 = int.Parse(Console.ReadLine());
                a[1, 3] = b8;
                Console.WriteLine("Введите число соответствующее пятому элементу столбца, второму элементу строки");
                b18 = int.Parse(Console.ReadLine());
                a[1, 4] = b18;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, второму элементу строки");
                b27 = int.Parse(Console.ReadLine());
                a[1, 5] = b27;
                Console.WriteLine("Введите число соответствующее первому элементу столбца, третьему элементу строки");
                b9 = int.Parse(Console.ReadLine());
                a[2, 0] = b9;
                Console.WriteLine("Введите число соответствующее второму элементу столбца, третьему элементу строки");
                b10 = int.Parse(Console.ReadLine());
                a[2, 1] = b10;
                Console.WriteLine("Введите число соответствующее третьему элементу столбца, третьему элементу строки");
                b11 = int.Parse(Console.ReadLine());
                a[2, 2] = b11;
                Console.WriteLine("Введите число соответствующее четвертому элементу столбца, третьему элементу строки");
                b12 = int.Parse(Console.ReadLine());
                a[2, 3] = b12;
                Console.WriteLine("Введите число соответствующее пятому элементу столбца, третьему элементу строки");
                b19 = int.Parse(Console.ReadLine());
                a[2, 4] = b19;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, третьему элементу строки");
                b28 = int.Parse(Console.ReadLine());
                a[2, 5] = b28;
                Console.WriteLine("Введите число соответствующее первому элементу столбца, четвертому элементу строки");
                b13 = int.Parse(Console.ReadLine());
                a[3, 0] = b13;
                Console.WriteLine("Введите число соответствующее второму элементу столбца, четвертому элементу строки");
                b14 = int.Parse(Console.ReadLine());
                a[3, 1] = b14;
                Console.WriteLine("Введите число соответствующее третьему элементу столбца, четвертому элементу строки");
                b15 = int.Parse(Console.ReadLine());
                a[3, 2] = b15;
                Console.WriteLine("Введите число соответствующее четвертому элементу столбца, четвертому элементу строки");
                b16 = int.Parse(Console.ReadLine());
                a[3, 3] = b16;
                Console.WriteLine("Введите число соответствующее пятому элементу столбца, четвертому элементу строки");
                b20 = int.Parse(Console.ReadLine());
                a[3, 4] = b20;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, четвертому элементу строки");
                b29 = int.Parse(Console.ReadLine());
                a[3, 5] = b29;
                Console.WriteLine("Введите число соответствующее первому элементу столбца, пятому элементу строки");
                b21 = int.Parse(Console.ReadLine());
                a[4, 0] = b21;
                Console.WriteLine("Введите число соответствующее второму элементу столбца, пятому элементу строки");
                b22 = int.Parse(Console.ReadLine());
                a[4, 1] = b22;
                Console.WriteLine("Введите число соответствующее третьему элементу столбца, пятому элементу строки");
                b23 = int.Parse(Console.ReadLine());
                a[4, 2] = b23;
                Console.WriteLine("Введите число соответствующее четвертому элементу столбца, пятому элементу строки");
                b24 = int.Parse(Console.ReadLine());
                a[4, 3] = b24;
                Console.WriteLine("Введите число соответствующее пятому элементу столбца, пятому элементу строки");
                b25 = int.Parse(Console.ReadLine());
                a[4, 4] = b25;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, пятому элементу строки");
                b30 = int.Parse(Console.ReadLine());
                a[4, 5] = b30;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, первому элементу строки");
                b31 = int.Parse(Console.ReadLine());
                a[5, 0] = b31;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, второму элементу строки");
                b32 = int.Parse(Console.ReadLine());
                a[5, 1] = b32;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, третьему элементу строки");
                b33 = int.Parse(Console.ReadLine());
                a[5, 2] = b33;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, четвертому элементу строки");
                b34 = int.Parse(Console.ReadLine());
                a[5, 3] = b34;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, пятому элементу строки");
                b35 = int.Parse(Console.ReadLine());
                a[5, 4] = b35;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, шестому элементу строки");
                b36 = int.Parse(Console.ReadLine());
                a[5, 5] = b36;
            }
            if (n == 7)
            {
                Console.WriteLine("Введите число соответствующее первому элементу столбца, первому элементу строки");
                b1 = int.Parse(Console.ReadLine());
                a[0, 0] = b1;
                Console.WriteLine("Введите число соответствующее второму элементу столбца, первому элементу строки");
                b2 = int.Parse(Console.ReadLine());
                a[0, 1] = b2;
                Console.WriteLine("Введите число соответствующее третьему элементу столбца, первому элементу строки");
                b3 = int.Parse(Console.ReadLine());
                a[0, 2] = b3;
                Console.WriteLine("Введите число соответствующее четвертому элементу столбца, первому элементу строки");
                b4 = int.Parse(Console.ReadLine());
                a[0, 3] = b4;
                Console.WriteLine("Введите число соответствующее пятому элементу столбца, первому элементу строки");
                b17 = int.Parse(Console.ReadLine());
                a[0, 4] = b17;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, первому элементу строки");
                b26 = int.Parse(Console.ReadLine());
                a[0, 5] = b26;
                Console.WriteLine("Введите число соответствующее седьмому элементу столбца, первому элементу строки");
                b37 = int.Parse(Console.ReadLine());
                a[0, 6] = b37;
                Console.WriteLine("Введите число соответствующее первому элементу столбца, второму элементу строки");
                b5 = int.Parse(Console.ReadLine());
                a[1, 0] = b5;
                Console.WriteLine("Введите число соответствующее второму элементу столбца, второму элементу строки");
                b6 = int.Parse(Console.ReadLine());
                a[1, 1] = b6;
                Console.WriteLine("Введите число соответствующее третьему элементу столбца, второму элементу строки");
                b7 = int.Parse(Console.ReadLine());
                a[1, 2] = b7;
                Console.WriteLine("Введите число соответствующее четвертому элементу столбца, второму элементу строки");
                b8 = int.Parse(Console.ReadLine());
                a[1, 3] = b8;
                Console.WriteLine("Введите число соответствующее пятому элементу столбца, второму элементу строки");
                b18 = int.Parse(Console.ReadLine());
                a[1, 4] = b18;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, второму элементу строки");
                b27 = int.Parse(Console.ReadLine());
                a[1, 5] = b27;
                Console.WriteLine("Введите число соответствующее седьмому элементу столбца, второму элементу строки");
                b38 = int.Parse(Console.ReadLine());
                a[1, 6] = b38;
                Console.WriteLine("Введите число соответствующее первому элементу столбца, третьему элементу строки");
                b9 = int.Parse(Console.ReadLine());
                a[2, 0] = b9;
                Console.WriteLine("Введите число соответствующее второму элементу столбца, третьему элементу строки");
                b10 = int.Parse(Console.ReadLine());
                a[2, 1] = b10;
                Console.WriteLine("Введите число соответствующее третьему элементу столбца, третьему элементу строки");
                b11 = int.Parse(Console.ReadLine());
                a[2, 2] = b11;
                Console.WriteLine("Введите число соответствующее четвертому элементу столбца, третьему элементу строки");
                b12 = int.Parse(Console.ReadLine());
                a[2, 3] = b12;
                Console.WriteLine("Введите число соответствующее пятому элементу столбца, третьему элементу строки");
                b19 = int.Parse(Console.ReadLine());
                a[2, 4] = b19;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, третьему элементу строки");
                b28 = int.Parse(Console.ReadLine());
                a[2, 5] = b28;
                Console.WriteLine("Введите число соответствующее седьмому элементу столбца, третьему элементу строки");
                b39 = int.Parse(Console.ReadLine());
                a[2, 6] = b39;
                Console.WriteLine("Введите число соответствующее первому элементу столбца, четвертому элементу строки");
                b13 = int.Parse(Console.ReadLine());
                a[3, 0] = b13;
                Console.WriteLine("Введите число соответствующее второму элементу столбца, четвертому элементу строки");
                b14 = int.Parse(Console.ReadLine());
                a[3, 1] = b14;
                Console.WriteLine("Введите число соответствующее третьему элементу столбца, четвертому элементу строки");
                b15 = int.Parse(Console.ReadLine());
                a[3, 2] = b15;
                Console.WriteLine("Введите число соответствующее четвертому элементу столбца, четвертому элементу строки");
                b16 = int.Parse(Console.ReadLine());
                a[3, 3] = b16;
                Console.WriteLine("Введите число соответствующее пятому элементу столбца, четвертому элементу строки");
                b20 = int.Parse(Console.ReadLine());
                a[3, 4] = b20;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, четвертому элементу строки");
                b29 = int.Parse(Console.ReadLine());
                a[3, 5] = b29;
                Console.WriteLine("Введите число соответствующее седьмому элементу столбца, четвертому элементу строки");
                b40 = int.Parse(Console.ReadLine());
                a[3, 6] = b40;
                Console.WriteLine("Введите число соответствующее первому элементу столбца, пятому элементу строки");
                b21 = int.Parse(Console.ReadLine());
                a[4, 0] = b21;
                Console.WriteLine("Введите число соответствующее второму элементу столбца, пятому элементу строки");
                b22 = int.Parse(Console.ReadLine());
                a[4, 1] = b22;
                Console.WriteLine("Введите число соответствующее третьему элементу столбца, пятому элементу строки");
                b23 = int.Parse(Console.ReadLine());
                a[4, 2] = b23;
                Console.WriteLine("Введите число соответствующее четвертому элементу столбца, пятому элементу строки");
                b24 = int.Parse(Console.ReadLine());
                a[4, 3] = b24;
                Console.WriteLine("Введите число соответствующее пятому элементу столбца, пятому элементу строки");
                b25 = int.Parse(Console.ReadLine());
                a[4, 4] = b25;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, пятому элементу строки");
                b30 = int.Parse(Console.ReadLine());
                a[4, 5] = b30;
                Console.WriteLine("Введите число соответствующее седьмому элементу столбца, пятому элементу строки");
                b41 = int.Parse(Console.ReadLine());
                a[4, 6] = b41;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, первому элементу строки");
                b31 = int.Parse(Console.ReadLine());
                a[5, 0] = b31;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, второму элементу строки");
                b32 = int.Parse(Console.ReadLine());
                a[5, 1] = b32;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, третьему элементу строки");
                b33 = int.Parse(Console.ReadLine());
                a[5, 2] = b33;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, четвертому элементу строки");
                b34 = int.Parse(Console.ReadLine());
                a[5, 3] = b34;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, пятому элементу строки");
                b35 = int.Parse(Console.ReadLine());
                a[5, 4] = b35;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, шестому элементу строки");
                b36 = int.Parse(Console.ReadLine());
                a[5, 5] = b36;
                Console.WriteLine("Введите число соответствующее седьмому элементу столбца, шестому элементу строки");
                b42 = int.Parse(Console.ReadLine());
                a[5, 6] = b42;
                Console.WriteLine("Введите число соответствующее первому элементу столбца, седьмому элементу строки");
                b43 = int.Parse(Console.ReadLine());
                a[6, 0] = b43;
                Console.WriteLine("Введите число соответствующее второму элементу столбца, седьмому элементу строки");
                b44 = int.Parse(Console.ReadLine());
                a[6, 1] = b44;
                Console.WriteLine("Введите число соответствующее третьему элементу столбца, седьмому элементу строки");
                b45 = int.Parse(Console.ReadLine());
                a[6, 2] = b45;
                Console.WriteLine("Введите число соответствующее четвертому элементу столбца, седьмому элементу строки");
                b46 = int.Parse(Console.ReadLine());
                a[6, 3] = b46;
                Console.WriteLine("Введите число соответствующее пятому элементу столбца, седьмому элементу строки");
                b47 = int.Parse(Console.ReadLine());
                a[6, 4] = b47;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, седьмому элементу строки");
                b48 = int.Parse(Console.ReadLine());
                a[6, 5] = b48;
                Console.WriteLine("Введите число соответствующее седьмому элементу столбца, седьмому элементу строки");
                b49 = int.Parse(Console.ReadLine());
                a[6, 6] = b49;
            }
            if (n == 8)
            {
                Console.WriteLine("Введите число соответствующее первому элементу столбца, первому элементу строки");
                b1 = int.Parse(Console.ReadLine());
                a[0, 0] = b1;
                Console.WriteLine("Введите число соответствующее второму элементу столбца, первому элементу строки");
                b2 = int.Parse(Console.ReadLine());
                a[0, 1] = b2;
                Console.WriteLine("Введите число соответствующее третьему элементу столбца, первому элементу строки");
                b3 = int.Parse(Console.ReadLine());
                a[0, 2] = b3;
                Console.WriteLine("Введите число соответствующее четвертому элементу столбца, первому элементу строки");
                b4 = int.Parse(Console.ReadLine());
                a[0, 3] = b4;
                Console.WriteLine("Введите число соответствующее пятому элементу столбца, первому элементу строки");
                b17 = int.Parse(Console.ReadLine());
                a[0, 4] = b17;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, первому элементу строки");
                b26 = int.Parse(Console.ReadLine());
                a[0, 5] = b26;
                Console.WriteLine("Введите число соответствующее седьмому элементу столбца, первому элементу строки");
                b37 = int.Parse(Console.ReadLine());
                a[0, 6] = b37;
                Console.WriteLine("Введите число соответствующее восьмому элементу столбца, первому элементу строки");
                b50 = int.Parse(Console.ReadLine());
                a[0, 7] = b50;
                Console.WriteLine("Введите число соответствующее первому элементу столбца, второму элементу строки");
                b5 = int.Parse(Console.ReadLine());
                a[1, 0] = b5;
                Console.WriteLine("Введите число соответствующее второму элементу столбца, второму элементу строки");
                b6 = int.Parse(Console.ReadLine());
                a[1, 1] = b6;
                Console.WriteLine("Введите число соответствующее третьему элементу столбца, второму элементу строки");
                b7 = int.Parse(Console.ReadLine());
                a[1, 2] = b7;
                Console.WriteLine("Введите число соответствующее четвертому элементу столбца, второму элементу строки");
                b8 = int.Parse(Console.ReadLine());
                a[1, 3] = b8;
                Console.WriteLine("Введите число соответствующее пятому элементу столбца, второму элементу строки");
                b18 = int.Parse(Console.ReadLine());
                a[1, 4] = b18;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, второму элементу строки");
                b27 = int.Parse(Console.ReadLine());
                a[1, 5] = b27;
                Console.WriteLine("Введите число соответствующее седьмому элементу столбца, второму элементу строки");
                b38 = int.Parse(Console.ReadLine());
                a[1, 6] = b38;
                Console.WriteLine("Введите число соответствующее восьмому элементу столбца, второму элементу строки");
                b51 = int.Parse(Console.ReadLine());
                a[1, 7] = b51;
                Console.WriteLine("Введите число соответствующее первому элементу столбца, третьему элементу строки");
                b9 = int.Parse(Console.ReadLine());
                a[2, 0] = b9;
                Console.WriteLine("Введите число соответствующее второму элементу столбца, третьему элементу строки");
                b10 = int.Parse(Console.ReadLine());
                a[2, 1] = b10;
                Console.WriteLine("Введите число соответствующее третьему элементу столбца, третьему элементу строки");
                b11 = int.Parse(Console.ReadLine());
                a[2, 2] = b11;
                Console.WriteLine("Введите число соответствующее четвертому элементу столбца, третьему элементу строки");
                b12 = int.Parse(Console.ReadLine());
                a[2, 3] = b12;
                Console.WriteLine("Введите число соответствующее пятому элементу столбца, третьему элементу строки");
                b19 = int.Parse(Console.ReadLine());
                a[2, 4] = b19;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, третьему элементу строки");
                b28 = int.Parse(Console.ReadLine());
                a[2, 5] = b28;
                Console.WriteLine("Введите число соответствующее седьмому элементу столбца, третьему элементу строки");
                b39 = int.Parse(Console.ReadLine());
                a[2, 6] = b39;
                Console.WriteLine("Введите число соответствующее восьмому элементу столбца, третьему элементу строки");
                b52 = int.Parse(Console.ReadLine());
                a[2, 7] = b52;
                Console.WriteLine("Введите число соответствующее первому элементу столбца, четвертому элементу строки");
                b13 = int.Parse(Console.ReadLine());
                a[3, 0] = b13;
                Console.WriteLine("Введите число соответствующее второму элементу столбца, четвертому элементу строки");
                b14 = int.Parse(Console.ReadLine());
                a[3, 1] = b14;
                Console.WriteLine("Введите число соответствующее третьему элементу столбца, четвертому элементу строки");
                b15 = int.Parse(Console.ReadLine());
                a[3, 2] = b15;
                Console.WriteLine("Введите число соответствующее четвертому элементу столбца, четвертому элементу строки");
                b16 = int.Parse(Console.ReadLine());
                a[3, 3] = b16;
                Console.WriteLine("Введите число соответствующее пятому элементу столбца, четвертому элементу строки");
                b20 = int.Parse(Console.ReadLine());
                a[3, 4] = b20;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, четвертому элементу строки");
                b29 = int.Parse(Console.ReadLine());
                a[3, 5] = b29;
                Console.WriteLine("Введите число соответствующее седьмому элементу столбца, четвертому элементу строки");
                b40 = int.Parse(Console.ReadLine());
                a[3, 6] = b40;
                Console.WriteLine("Введите число соответствующее восьмому элементу столбца, четвертому элементу строки");
                b53 = int.Parse(Console.ReadLine());
                a[3, 7] = b53;
                Console.WriteLine("Введите число соответствующее первому элементу столбца, пятому элементу строки");
                b21 = int.Parse(Console.ReadLine());
                a[4, 0] = b21;
                Console.WriteLine("Введите число соответствующее второму элементу столбца, пятому элементу строки");
                b22 = int.Parse(Console.ReadLine());
                a[4, 1] = b22;
                Console.WriteLine("Введите число соответствующее третьему элементу столбца, пятому элементу строки");
                b23 = int.Parse(Console.ReadLine());
                a[4, 2] = b23;
                Console.WriteLine("Введите число соответствующее четвертому элементу столбца, пятому элементу строки");
                b24 = int.Parse(Console.ReadLine());
                a[4, 3] = b24;
                Console.WriteLine("Введите число соответствующее пятому элементу столбца, пятому элементу строки");
                b25 = int.Parse(Console.ReadLine());
                a[4, 4] = b25;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, пятому элементу строки");
                b30 = int.Parse(Console.ReadLine());
                a[4, 5] = b30;
                Console.WriteLine("Введите число соответствующее седьмому элементу столбца, пятому элементу строки");
                b41 = int.Parse(Console.ReadLine());
                a[4, 6] = b41;
                Console.WriteLine("Введите число соответствующее восьмому элементу столбца, пятому элементу строки");
                b54 = int.Parse(Console.ReadLine());
                a[4, 7] = b54;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, первому элементу строки");
                b31 = int.Parse(Console.ReadLine());
                a[5, 0] = b31;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, второму элементу строки");
                b32 = int.Parse(Console.ReadLine());
                a[5, 1] = b32;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, третьему элементу строки");
                b33 = int.Parse(Console.ReadLine());
                a[5, 2] = b33;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, четвертому элементу строки");
                b34 = int.Parse(Console.ReadLine());
                a[5, 3] = b34;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, пятому элементу строки");
                b35 = int.Parse(Console.ReadLine());
                a[5, 4] = b35;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, шестому элементу строки");
                b36 = int.Parse(Console.ReadLine());
                a[5, 5] = b36;
                Console.WriteLine("Введите число соответствующее седьмому элементу столбца, шестому элементу строки");
                b42 = int.Parse(Console.ReadLine());
                a[5, 6] = b42;
                Console.WriteLine("Введите число соответствующее восьмому элементу столбца, шестому элементу строки");
                b55 = int.Parse(Console.ReadLine());
                a[5, 7] = b55;
                Console.WriteLine("Введите число соответствующее первому элементу столбца, седьмому элементу строки");
                b43 = int.Parse(Console.ReadLine());
                a[6, 0] = b43;
                Console.WriteLine("Введите число соответствующее второму элементу столбца, седьмому элементу строки");
                b44 = int.Parse(Console.ReadLine());
                a[6, 1] = b44;
                Console.WriteLine("Введите число соответствующее третьему элементу столбца, седьмому элементу строки");
                b45 = int.Parse(Console.ReadLine());
                a[6, 2] = b45;
                Console.WriteLine("Введите число соответствующее четвертому элементу столбца, седьмому элементу строки");
                b46 = int.Parse(Console.ReadLine());
                a[6, 3] = b46;
                Console.WriteLine("Введите число соответствующее пятому элементу столбца, седьмому элементу строки");
                b47 = int.Parse(Console.ReadLine());
                a[6, 4] = b47;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, седьмому элементу строки");
                b48 = int.Parse(Console.ReadLine());
                a[6, 5] = b48;
                Console.WriteLine("Введите число соответствующее седьмому элементу столбца, седьмому элементу строки");
                b49 = int.Parse(Console.ReadLine());
                a[6, 6] = b49;
                Console.WriteLine("Введите число соответствующее восьмому элементу столбца, седьмому элементу строки");
                b56 = int.Parse(Console.ReadLine());
                a[6, 7] = b56;
                Console.WriteLine("Введите число соответствующее первому элементу столбца, восьмому элементу строки");
                b57 = int.Parse(Console.ReadLine());
                a[7, 0] = b57;
                Console.WriteLine("Введите число соответствующее второму элементу столбца, восьмому элементу строки");
                b58 = int.Parse(Console.ReadLine());
                a[7, 1] = b58;
                Console.WriteLine("Введите число соответствующее третьему элементу столбца, восьмому элементу строки");
                b59 = int.Parse(Console.ReadLine());
                a[7, 2] = b59;
                Console.WriteLine("Введите число соответствующее четвертому элементу столбца, восьмому элементу строки");
                b60 = int.Parse(Console.ReadLine());
                a[7, 3] = b60;
                Console.WriteLine("Введите число соответствующее пятому элементу столбца, восьмому элементу строки");
                b61 = int.Parse(Console.ReadLine());
                a[7, 4] = b61;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, восьмому элементу строки");
                b62 = int.Parse(Console.ReadLine());
                a[7, 5] = b62;
                Console.WriteLine("Введите число соответствующее седьмому элементу столбца, восьмому элементу строки");
                b63 = int.Parse(Console.ReadLine());
                a[7, 6] = b63;
                Console.WriteLine("Введите число соответствующее восьмому элементу столбца, восьмому элементу строки");
                b64 = int.Parse(Console.ReadLine());
                a[7, 7] = b64;
            }
            if (n == 9)
            {
                Console.WriteLine("Введите число соответствующее первому элементу столбца, первому элементу строки");
                b1 = int.Parse(Console.ReadLine());
                a[0, 0] = b1;
                Console.WriteLine("Введите число соответствующее второму элементу столбца, первому элементу строки");
                b2 = int.Parse(Console.ReadLine());
                a[0, 1] = b2;
                Console.WriteLine("Введите число соответствующее третьему элементу столбца, первому элементу строки");
                b3 = int.Parse(Console.ReadLine());
                a[0, 2] = b3;
                Console.WriteLine("Введите число соответствующее четвертому элементу столбца, первому элементу строки");
                b4 = int.Parse(Console.ReadLine());
                a[0, 3] = b4;
                Console.WriteLine("Введите число соответствующее пятому элементу столбца, первому элементу строки");
                b17 = int.Parse(Console.ReadLine());
                a[0, 4] = b17;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, первому элементу строки");
                b26 = int.Parse(Console.ReadLine());
                a[0, 5] = b26;
                Console.WriteLine("Введите число соответствующее седьмому элементу столбца, первому элементу строки");
                b37 = int.Parse(Console.ReadLine());
                a[0, 6] = b37;
                Console.WriteLine("Введите число соответствующее восьмому элементу столбца, первому элементу строки");
                b50 = int.Parse(Console.ReadLine());
                a[0, 7] = b50;
                Console.WriteLine("Введите число соответствующее девятому элементу столбца, первому элементу строки");
                b65 = int.Parse(Console.ReadLine());
                a[0, 8] = b65;
                Console.WriteLine("Введите число соответствующее первому элементу столбца, второму элементу строки");
                b5 = int.Parse(Console.ReadLine());
                a[1, 0] = b5;
                Console.WriteLine("Введите число соответствующее второму элементу столбца, второму элементу строки");
                b6 = int.Parse(Console.ReadLine());
                a[1, 1] = b6;
                Console.WriteLine("Введите число соответствующее третьему элементу столбца, второму элементу строки");
                b7 = int.Parse(Console.ReadLine());
                a[1, 2] = b7;
                Console.WriteLine("Введите число соответствующее четвертому элементу столбца, второму элементу строки");
                b8 = int.Parse(Console.ReadLine());
                a[1, 3] = b8;
                Console.WriteLine("Введите число соответствующее пятому элементу столбца, второму элементу строки");
                b18 = int.Parse(Console.ReadLine());
                a[1, 4] = b18;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, второму элементу строки");
                b27 = int.Parse(Console.ReadLine());
                a[1, 5] = b27;
                Console.WriteLine("Введите число соответствующее седьмому элементу столбца, второму элементу строки");
                b38 = int.Parse(Console.ReadLine());
                a[1, 6] = b38;
                Console.WriteLine("Введите число соответствующее восьмому элементу столбца, второму элементу строки");
                b51 = int.Parse(Console.ReadLine());
                a[1, 7] = b51;
                Console.WriteLine("Введите число соответствующее девятому элементу столбца, второму элементу строки");
                b66 = int.Parse(Console.ReadLine());
                a[1, 8] = b66;
                Console.WriteLine("Введите число соответствующее первому элементу столбца, третьему элементу строки");
                b9 = int.Parse(Console.ReadLine());
                a[2, 0] = b9;
                Console.WriteLine("Введите число соответствующее второму элементу столбца, третьему элементу строки");
                b10 = int.Parse(Console.ReadLine());
                a[2, 1] = b10;
                Console.WriteLine("Введите число соответствующее третьему элементу столбца, третьему элементу строки");
                b11 = int.Parse(Console.ReadLine());
                a[2, 2] = b11;
                Console.WriteLine("Введите число соответствующее четвертому элементу столбца, третьему элементу строки");
                b12 = int.Parse(Console.ReadLine());
                a[2, 3] = b12;
                Console.WriteLine("Введите число соответствующее пятому элементу столбца, третьему элементу строки");
                b19 = int.Parse(Console.ReadLine());
                a[2, 4] = b19;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, третьему элементу строки");
                b28 = int.Parse(Console.ReadLine());
                a[2, 5] = b28;
                Console.WriteLine("Введите число соответствующее седьмому элементу столбца, третьему элементу строки");
                b39 = int.Parse(Console.ReadLine());
                a[2, 6] = b39;
                Console.WriteLine("Введите число соответствующее восьмому элементу столбца, третьему элементу строки");
                b52 = int.Parse(Console.ReadLine());
                a[2, 7] = b52;
                Console.WriteLine("Введите число соответствующее девятому элементу столбца, третьему элементу строки");
                b67 = int.Parse(Console.ReadLine());
                a[2, 8] = b67;
                Console.WriteLine("Введите число соответствующее первому элементу столбца, четвертому элементу строки");
                b13 = int.Parse(Console.ReadLine());
                a[3, 0] = b13;
                Console.WriteLine("Введите число соответствующее второму элементу столбца, четвертому элементу строки");
                b14 = int.Parse(Console.ReadLine());
                a[3, 1] = b14;
                Console.WriteLine("Введите число соответствующее третьему элементу столбца, четвертому элементу строки");
                b15 = int.Parse(Console.ReadLine());
                a[3, 2] = b15;
                Console.WriteLine("Введите число соответствующее четвертому элементу столбца, четвертому элементу строки");
                b16 = int.Parse(Console.ReadLine());
                a[3, 3] = b16;
                Console.WriteLine("Введите число соответствующее пятому элементу столбца, четвертому элементу строки");
                b20 = int.Parse(Console.ReadLine());
                a[3, 4] = b20;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, четвертому элементу строки");
                b29 = int.Parse(Console.ReadLine());
                a[3, 5] = b29;
                Console.WriteLine("Введите число соответствующее седьмому элементу столбца, четвертому элементу строки");
                b40 = int.Parse(Console.ReadLine());
                a[3, 6] = b40;
                Console.WriteLine("Введите число соответствующее восьмому элементу столбца, четвертому элементу строки");
                b53 = int.Parse(Console.ReadLine());
                a[3, 7] = b53;
                Console.WriteLine("Введите число соответствующее девятому элементу столбца, четвертому элементу строки");
                b68 = int.Parse(Console.ReadLine());
                a[3, 8] = b68;
                Console.WriteLine("Введите число соответствующее первому элементу столбца, пятому элементу строки");
                b21 = int.Parse(Console.ReadLine());
                a[4, 0] = b21;
                Console.WriteLine("Введите число соответствующее второму элементу столбца, пятому элементу строки");
                b22 = int.Parse(Console.ReadLine());
                a[4, 1] = b22;
                Console.WriteLine("Введите число соответствующее третьему элементу столбца, пятому элементу строки");
                b23 = int.Parse(Console.ReadLine());
                a[4, 2] = b23;
                Console.WriteLine("Введите число соответствующее четвертому элементу столбца, пятому элементу строки");
                b24 = int.Parse(Console.ReadLine());
                a[4, 3] = b24;
                Console.WriteLine("Введите число соответствующее пятому элементу столбца, пятому элементу строки");
                b25 = int.Parse(Console.ReadLine());
                a[4, 4] = b25;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, пятому элементу строки");
                b30 = int.Parse(Console.ReadLine());
                a[4, 5] = b30;
                Console.WriteLine("Введите число соответствующее седьмому элементу столбца, пятому элементу строки");
                b41 = int.Parse(Console.ReadLine());
                a[4, 6] = b41;
                Console.WriteLine("Введите число соответствующее восьмому элементу столбца, пятому элементу строки");
                b54 = int.Parse(Console.ReadLine());
                a[4, 7] = b54;
                Console.WriteLine("Введите число соответствующее девятому элементу столбца, пятому элементу строки");
                b69 = int.Parse(Console.ReadLine());
                a[4, 8] = b69;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, первому элементу строки");
                b31 = int.Parse(Console.ReadLine());
                a[5, 0] = b31;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, второму элементу строки");
                b32 = int.Parse(Console.ReadLine());
                a[5, 1] = b32;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, третьему элементу строки");
                b33 = int.Parse(Console.ReadLine());
                a[5, 2] = b33;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, четвертому элементу строки");
                b34 = int.Parse(Console.ReadLine());
                a[5, 3] = b34;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, пятому элементу строки");
                b35 = int.Parse(Console.ReadLine());
                a[5, 4] = b35;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, шестому элементу строки");
                b36 = int.Parse(Console.ReadLine());
                a[5, 5] = b36;
                Console.WriteLine("Введите число соответствующее седьмому элементу столбца, шестому элементу строки");
                b42 = int.Parse(Console.ReadLine());
                a[5, 6] = b42;
                Console.WriteLine("Введите число соответствующее восьмому элементу столбца, шестому элементу строки");
                b55 = int.Parse(Console.ReadLine());
                a[5, 7] = b55;
                Console.WriteLine("Введите число соответствующее девятому элементу столбца, шестому элементу строки");
                b70 = int.Parse(Console.ReadLine());
                a[5, 8] = b70;
                Console.WriteLine("Введите число соответствующее первому элементу столбца, седьмому элементу строки");
                b43 = int.Parse(Console.ReadLine());
                a[6, 0] = b43;
                Console.WriteLine("Введите число соответствующее второму элементу столбца, седьмому элементу строки");
                b44 = int.Parse(Console.ReadLine());
                a[6, 1] = b44;
                Console.WriteLine("Введите число соответствующее третьему элементу столбца, седьмому элементу строки");
                b45 = int.Parse(Console.ReadLine());
                a[6, 2] = b45;
                Console.WriteLine("Введите число соответствующее четвертому элементу столбца, седьмому элементу строки");
                b46 = int.Parse(Console.ReadLine());
                a[6, 3] = b46;
                Console.WriteLine("Введите число соответствующее пятому элементу столбца, седьмому элементу строки");
                b47 = int.Parse(Console.ReadLine());
                a[6, 4] = b47;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, седьмому элементу строки");
                b48 = int.Parse(Console.ReadLine());
                a[6, 5] = b48;
                Console.WriteLine("Введите число соответствующее седьмому элементу столбца, седьмому элементу строки");
                b49 = int.Parse(Console.ReadLine());
                a[6, 6] = b49;
                Console.WriteLine("Введите число соответствующее восьмому элементу столбца, седьмому элементу строки");
                b56 = int.Parse(Console.ReadLine());
                a[6, 7] = b56;
                Console.WriteLine("Введите число соответствующее девятому элементу столбца, седьмому элементу строки");
                b71 = int.Parse(Console.ReadLine());
                a[6, 8] = b71;
                Console.WriteLine("Введите число соответствующее первому элементу столбца, восьмому элементу строки");
                b57 = int.Parse(Console.ReadLine());
                a[7, 0] = b57;
                Console.WriteLine("Введите число соответствующее второму элементу столбца, восьмому элементу строки");
                b58 = int.Parse(Console.ReadLine());
                a[7, 1] = b58;
                Console.WriteLine("Введите число соответствующее третьему элементу столбца, восьмому элементу строки");
                b59 = int.Parse(Console.ReadLine());
                a[7, 2] = b59;
                Console.WriteLine("Введите число соответствующее четвертому элементу столбца, восьмому элементу строки");
                b60 = int.Parse(Console.ReadLine());
                a[7, 3] = b60;
                Console.WriteLine("Введите число соответствующее пятому элементу столбца, восьмому элементу строки");
                b61 = int.Parse(Console.ReadLine());
                a[7, 4] = b61;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, восьмому элементу строки");
                b62 = int.Parse(Console.ReadLine());
                a[7, 5] = b62;
                Console.WriteLine("Введите число соответствующее седьмому элементу столбца, восьмому элементу строки");
                b63 = int.Parse(Console.ReadLine());
                a[7, 6] = b63;
                Console.WriteLine("Введите число соответствующее восьмому элементу столбца, восьмому элементу строки");
                b64 = int.Parse(Console.ReadLine());
                a[7, 7] = b64;
                Console.WriteLine("Введите число соответствующее девятому элементу столбца, восьмому элементу строки");
                b72 = int.Parse(Console.ReadLine());
                a[7, 8] = b72;
                Console.WriteLine("Введите число соответствующее первому элементу столбца, девятому элементу строки");
                b73 = int.Parse(Console.ReadLine());
                a[8, 0] = b73;
                Console.WriteLine("Введите число соответствующее второму элементу столбца, девятому элементу строки");
                b74 = int.Parse(Console.ReadLine());
                a[8, 1] = b74;
                Console.WriteLine("Введите число соответствующее третьему элементу столбца, девятому элементу строки");
                b75 = int.Parse(Console.ReadLine());
                a[8, 2] = b75;
                Console.WriteLine("Введите число соответствующее четвертому элементу столбца, девятому элементу строки");
                b76 = int.Parse(Console.ReadLine());
                a[8, 3] = b76;
                Console.WriteLine("Введите число соответствующее пятому элементу столбца, девятому элементу строки");
                b77 = int.Parse(Console.ReadLine());
                a[8, 4] = b77;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, девятому элементу строки");
                b78 = int.Parse(Console.ReadLine());
                a[8, 5] = b78;
                Console.WriteLine("Введите число соответствующее седьмому элементу столбца, девятому элементу строки");
                b79 = int.Parse(Console.ReadLine());
                a[8, 6] = b79;
                Console.WriteLine("Введите число соответствующее восьмому элементу столбца, девятому элементу строки");
                b80 = int.Parse(Console.ReadLine());
                a[8, 7] = b80;
                Console.WriteLine("Введите число соответствующее девятому элементу столбца, девятому элементу строки");
                b81 = int.Parse(Console.ReadLine());
                a[8, 8] = b81;
            }
            if (n == 10)
            {
                Console.WriteLine("Введите число соответствующее первому элементу столбца, первому элементу строки");
                b1 = int.Parse(Console.ReadLine());
                a[0, 0] = b1;
                Console.WriteLine("Введите число соответствующее второму элементу столбца, первому элементу строки");
                b2 = int.Parse(Console.ReadLine());
                a[0, 1] = b2;
                Console.WriteLine("Введите число соответствующее третьему элементу столбца, первому элементу строки");
                b3 = int.Parse(Console.ReadLine());
                a[0, 2] = b3;
                Console.WriteLine("Введите число соответствующее четвертому элементу столбца, первому элементу строки");
                b4 = int.Parse(Console.ReadLine());
                a[0, 3] = b4;
                Console.WriteLine("Введите число соответствующее пятому элементу столбца, первому элементу строки");
                b17 = int.Parse(Console.ReadLine());
                a[0, 4] = b17;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, первому элементу строки");
                b26 = int.Parse(Console.ReadLine());
                a[0, 5] = b26;
                Console.WriteLine("Введите число соответствующее седьмому элементу столбца, первому элементу строки");
                b37 = int.Parse(Console.ReadLine());
                a[0, 6] = b37;
                Console.WriteLine("Введите число соответствующее восьмому элементу столбца, первому элементу строки");
                b50 = int.Parse(Console.ReadLine());
                a[0, 7] = b50;
                Console.WriteLine("Введите число соответствующее девятому элементу столбца, первому элементу строки");
                b65 = int.Parse(Console.ReadLine());
                a[0, 8] = b65;
                Console.WriteLine("Введите число соответствующее десятому элементу столбца, первому элементу строки");
                b82 = int.Parse(Console.ReadLine());
                a[0, 9] = b82;
                Console.WriteLine("Введите число соответствующее первому элементу столбца, второму элементу строки");
                b5 = int.Parse(Console.ReadLine());
                a[1, 0] = b5;
                Console.WriteLine("Введите число соответствующее второму элементу столбца, второму элементу строки");
                b6 = int.Parse(Console.ReadLine());
                a[1, 1] = b6;
                Console.WriteLine("Введите число соответствующее третьему элементу столбца, второму элементу строки");
                b7 = int.Parse(Console.ReadLine());
                a[1, 2] = b7;
                Console.WriteLine("Введите число соответствующее четвертому элементу столбца, второму элементу строки");
                b8 = int.Parse(Console.ReadLine());
                a[1, 3] = b8;
                Console.WriteLine("Введите число соответствующее пятому элементу столбца, второму элементу строки");
                b18 = int.Parse(Console.ReadLine());
                a[1, 4] = b18;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, второму элементу строки");
                b27 = int.Parse(Console.ReadLine());
                a[1, 5] = b27;
                Console.WriteLine("Введите число соответствующее седьмому элементу столбца, второму элементу строки");
                b38 = int.Parse(Console.ReadLine());
                a[1, 6] = b38;
                Console.WriteLine("Введите число соответствующее восьмому элементу столбца, второму элементу строки");
                b51 = int.Parse(Console.ReadLine());
                a[1, 7] = b51;
                Console.WriteLine("Введите число соответствующее девятому элементу столбца, второму элементу строки");
                b66 = int.Parse(Console.ReadLine());
                a[1, 8] = b66;
                Console.WriteLine("Введите число соответствующее десятому элементу столбца, второму элементу строки");
                b83 = int.Parse(Console.ReadLine());
                a[1, 9] = b83;
                Console.WriteLine("Введите число соответствующее первому элементу столбца, третьему элементу строки");
                b9 = int.Parse(Console.ReadLine());
                a[2, 0] = b9;
                Console.WriteLine("Введите число соответствующее второму элементу столбца, третьему элементу строки");
                b10 = int.Parse(Console.ReadLine());
                a[2, 1] = b10;
                Console.WriteLine("Введите число соответствующее третьему элементу столбца, третьему элементу строки");
                b11 = int.Parse(Console.ReadLine());
                a[2, 2] = b11;
                Console.WriteLine("Введите число соответствующее четвертому элементу столбца, третьему элементу строки");
                b12 = int.Parse(Console.ReadLine());
                a[2, 3] = b12;
                Console.WriteLine("Введите число соответствующее пятому элементу столбца, третьему элементу строки");
                b19 = int.Parse(Console.ReadLine());
                a[2, 4] = b19;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, третьему элементу строки");
                b28 = int.Parse(Console.ReadLine());
                a[2, 5] = b28;
                Console.WriteLine("Введите число соответствующее седьмому элементу столбца, третьему элементу строки");
                b39 = int.Parse(Console.ReadLine());
                a[2, 6] = b39;
                Console.WriteLine("Введите число соответствующее восьмому элементу столбца, третьему элементу строки");
                b52 = int.Parse(Console.ReadLine());
                a[2, 7] = b52;
                Console.WriteLine("Введите число соответствующее девятому элементу столбца, третьему элементу строки");
                b67 = int.Parse(Console.ReadLine());
                a[2, 8] = b67;
                Console.WriteLine("Введите число соответствующее десятому элементу столбца, третьему элементу строки");
                b84 = int.Parse(Console.ReadLine());
                a[2, 9] = b84;
                Console.WriteLine("Введите число соответствующее первому элементу столбца, четвертому элементу строки");
                b13 = int.Parse(Console.ReadLine());
                a[3, 0] = b13;
                Console.WriteLine("Введите число соответствующее второму элементу столбца, четвертому элементу строки");
                b14 = int.Parse(Console.ReadLine());
                a[3, 1] = b14;
                Console.WriteLine("Введите число соответствующее третьему элементу столбца, четвертому элементу строки");
                b15 = int.Parse(Console.ReadLine());
                a[3, 2] = b15;
                Console.WriteLine("Введите число соответствующее четвертому элементу столбца, четвертому элементу строки");
                b16 = int.Parse(Console.ReadLine());
                a[3, 3] = b16;
                Console.WriteLine("Введите число соответствующее пятому элементу столбца, четвертому элементу строки");
                b20 = int.Parse(Console.ReadLine());
                a[3, 4] = b20;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, четвертому элементу строки");
                b29 = int.Parse(Console.ReadLine());
                a[3, 5] = b29;
                Console.WriteLine("Введите число соответствующее седьмому элементу столбца, четвертому элементу строки");
                b40 = int.Parse(Console.ReadLine());
                a[3, 6] = b40;
                Console.WriteLine("Введите число соответствующее восьмому элементу столбца, четвертому элементу строки");
                b53 = int.Parse(Console.ReadLine());
                a[3, 7] = b53;
                Console.WriteLine("Введите число соответствующее девятому элементу столбца, четвертому элементу строки");
                b68 = int.Parse(Console.ReadLine());
                a[3, 8] = b68;
                Console.WriteLine("Введите число соответствующее десятому элементу столбца, четвертому элементу строки");
                b85 = int.Parse(Console.ReadLine());
                a[3, 9] = b85;
                Console.WriteLine("Введите число соответствующее первому элементу столбца, пятому элементу строки");
                b21 = int.Parse(Console.ReadLine());
                a[4, 0] = b21;
                Console.WriteLine("Введите число соответствующее второму элементу столбца, пятому элементу строки");
                b22 = int.Parse(Console.ReadLine());
                a[4, 1] = b22;
                Console.WriteLine("Введите число соответствующее третьему элементу столбца, пятому элементу строки");
                b23 = int.Parse(Console.ReadLine());
                a[4, 2] = b23;
                Console.WriteLine("Введите число соответствующее четвертому элементу столбца, пятому элементу строки");
                b24 = int.Parse(Console.ReadLine());
                a[4, 3] = b24;
                Console.WriteLine("Введите число соответствующее пятому элементу столбца, пятому элементу строки");
                b25 = int.Parse(Console.ReadLine());
                a[4, 4] = b25;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, пятому элементу строки");
                b30 = int.Parse(Console.ReadLine());
                a[4, 5] = b30;
                Console.WriteLine("Введите число соответствующее седьмому элементу столбца, пятому элементу строки");
                b41 = int.Parse(Console.ReadLine());
                a[4, 6] = b41;
                Console.WriteLine("Введите число соответствующее восьмому элементу столбца, пятому элементу строки");
                b54 = int.Parse(Console.ReadLine());
                a[4, 7] = b54;
                Console.WriteLine("Введите число соответствующее девятому элементу столбца, пятому элементу строки");
                b69 = int.Parse(Console.ReadLine());
                a[4, 8] = b69;
                Console.WriteLine("Введите число соответствующее десятому элементу столбца, пятому элементу строки");
                b86 = int.Parse(Console.ReadLine());
                a[4, 9] = b86;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, первому элементу строки");
                b31 = int.Parse(Console.ReadLine());
                a[5, 0] = b31;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, второму элементу строки");
                b32 = int.Parse(Console.ReadLine());
                a[5, 1] = b32;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, третьему элементу строки");
                b33 = int.Parse(Console.ReadLine());
                a[5, 2] = b33;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, четвертому элементу строки");
                b34 = int.Parse(Console.ReadLine());
                a[5, 3] = b34;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, пятому элементу строки");
                b35 = int.Parse(Console.ReadLine());
                a[5, 4] = b35;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, шестому элементу строки");
                b36 = int.Parse(Console.ReadLine());
                a[5, 5] = b36;
                Console.WriteLine("Введите число соответствующее седьмому элементу столбца, шестому элементу строки");
                b42 = int.Parse(Console.ReadLine());
                a[5, 6] = b42;
                Console.WriteLine("Введите число соответствующее восьмому элементу столбца, шестому элементу строки");
                b55 = int.Parse(Console.ReadLine());
                a[5, 7] = b55;
                Console.WriteLine("Введите число соответствующее девятому элементу столбца, шестому элементу строки");
                b70 = int.Parse(Console.ReadLine());
                a[5, 8] = b70;
                Console.WriteLine("Введите число соответствующее десятому элементу столбца, шестому элементу строки");
                b87 = int.Parse(Console.ReadLine());
                a[5, 9] = b87;
                Console.WriteLine("Введите число соответствующее первому элементу столбца, седьмому элементу строки");
                b43 = int.Parse(Console.ReadLine());
                a[6, 0] = b43;
                Console.WriteLine("Введите число соответствующее второму элементу столбца, седьмому элементу строки");
                b44 = int.Parse(Console.ReadLine());
                a[6, 1] = b44;
                Console.WriteLine("Введите число соответствующее третьему элементу столбца, седьмому элементу строки");
                b45 = int.Parse(Console.ReadLine());
                a[6, 2] = b45;
                Console.WriteLine("Введите число соответствующее четвертому элементу столбца, седьмому элементу строки");
                b46 = int.Parse(Console.ReadLine());
                a[6, 3] = b46;
                Console.WriteLine("Введите число соответствующее пятому элементу столбца, седьмому элементу строки");
                b47 = int.Parse(Console.ReadLine());
                a[6, 4] = b47;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, седьмому элементу строки");
                b48 = int.Parse(Console.ReadLine());
                a[6, 5] = b48;
                Console.WriteLine("Введите число соответствующее седьмому элементу столбца, седьмому элементу строки");
                b49 = int.Parse(Console.ReadLine());
                a[6, 6] = b49;
                Console.WriteLine("Введите число соответствующее восьмому элементу столбца, седьмому элементу строки");
                b56 = int.Parse(Console.ReadLine());
                a[6, 7] = b56;
                Console.WriteLine("Введите число соответствующее девятому элементу столбца, седьмому элементу строки");
                b71 = int.Parse(Console.ReadLine());
                a[6, 8] = b71;
                Console.WriteLine("Введите число соответствующее десятому элементу столбца, седьмому элементу строки");
                b88 = int.Parse(Console.ReadLine());
                a[6, 9] = b88;
                Console.WriteLine("Введите число соответствующее первому элементу столбца, восьмому элементу строки");
                b57 = int.Parse(Console.ReadLine());
                a[7, 0] = b57;
                Console.WriteLine("Введите число соответствующее второму элементу столбца, восьмому элементу строки");
                b58 = int.Parse(Console.ReadLine());
                a[7, 1] = b58;
                Console.WriteLine("Введите число соответствующее третьему элементу столбца, восьмому элементу строки");
                b59 = int.Parse(Console.ReadLine());
                a[7, 2] = b59;
                Console.WriteLine("Введите число соответствующее четвертому элементу столбца, восьмому элементу строки");
                b60 = int.Parse(Console.ReadLine());
                a[7, 3] = b60;
                Console.WriteLine("Введите число соответствующее пятому элементу столбца, восьмому элементу строки");
                b61 = int.Parse(Console.ReadLine());
                a[7, 4] = b61;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, восьмому элементу строки");
                b62 = int.Parse(Console.ReadLine());
                a[7, 5] = b62;
                Console.WriteLine("Введите число соответствующее седьмому элементу столбца, восьмому элементу строки");
                b63 = int.Parse(Console.ReadLine());
                a[7, 6] = b63;
                Console.WriteLine("Введите число соответствующее восьмому элементу столбца, восьмому элементу строки");
                b64 = int.Parse(Console.ReadLine());
                a[7, 7] = b64;
                Console.WriteLine("Введите число соответствующее девятому элементу столбца, восьмому элементу строки");
                b72 = int.Parse(Console.ReadLine());
                a[7, 8] = b72;
                Console.WriteLine("Введите число соответствующее десятому элементу столбца, восьмому элементу строки");
                b89 = int.Parse(Console.ReadLine());
                a[7, 9] = b89;
                Console.WriteLine("Введите число соответствующее первому элементу столбца, девятому элементу строки");
                b73 = int.Parse(Console.ReadLine());
                a[8, 0] = b73;
                Console.WriteLine("Введите число соответствующее второму элементу столбца, девятому элементу строки");
                b74 = int.Parse(Console.ReadLine());
                a[8, 1] = b74;
                Console.WriteLine("Введите число соответствующее третьему элементу столбца, девятому элементу строки");
                b75 = int.Parse(Console.ReadLine());
                a[8, 2] = b75;
                Console.WriteLine("Введите число соответствующее четвертому элементу столбца, девятому элементу строки");
                b76 = int.Parse(Console.ReadLine());
                a[8, 3] = b76;
                Console.WriteLine("Введите число соответствующее пятому элементу столбца, девятому элементу строки");
                b77 = int.Parse(Console.ReadLine());
                a[8, 4] = b77;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, девятому элементу строки");
                b78 = int.Parse(Console.ReadLine());
                a[8, 5] = b78;
                Console.WriteLine("Введите число соответствующее седьмому элементу столбца, девятому элементу строки");
                b79 = int.Parse(Console.ReadLine());
                a[8, 6] = b79;
                Console.WriteLine("Введите число соответствующее восьмому элементу столбца, девятому элементу строки");
                b80 = int.Parse(Console.ReadLine());
                a[8, 7] = b80;
                Console.WriteLine("Введите число соответствующее девятому элементу столбца, девятому элементу строки");
                b81 = int.Parse(Console.ReadLine());
                a[8, 8] = b81;
                Console.WriteLine("Введите число соответствующее десятому элементу столбца, девятому элементу строки");
                b90 = int.Parse(Console.ReadLine());
                a[8, 9] = b90;
                Console.WriteLine("Введите число соответствующее первому элементу столбца, десятому элементу строки");
                b91 = int.Parse(Console.ReadLine());
                a[9, 0] = b91;
                Console.WriteLine("Введите число соответствующее второму элементу столбца, десятому элементу строки");
                b92 = int.Parse(Console.ReadLine());
                a[9, 1] = b92;
                Console.WriteLine("Введите число соответствующее третьему элементу столбца, десятому элементу строки");
                b93 = int.Parse(Console.ReadLine());
                a[9, 2] = b93;
                Console.WriteLine("Введите число соответствующее четвертому элементу столбца, десятому элементу строки");
                b94 = int.Parse(Console.ReadLine());
                a[9, 3] = b94;
                Console.WriteLine("Введите число соответствующее пятому элементу столбца, десятому элементу строки");
                b95 = int.Parse(Console.ReadLine());
                a[9, 4] = b95;
                Console.WriteLine("Введите число соответствующее шестому элементу столбца, десятому элементу строки");
                b96 = int.Parse(Console.ReadLine());
                a[9, 5] = b96;
                Console.WriteLine("Введите число соответствующее седьмому элементу столбца, десятому элементу строки");
                b97 = int.Parse(Console.ReadLine());
                a[9, 6] = b97;
                Console.WriteLine("Введите число соответствующее восьмому элементу столбца, десятому элементу строки");
                b98 = int.Parse(Console.ReadLine());
                a[9, 7] = b98;
                Console.WriteLine("Введите число соответствующее девятому элементу столбца, десятому элементу строки");
                b99 = int.Parse(Console.ReadLine());
                a[9, 8] = b99;
                Console.WriteLine("Введите число соответствующее десятому элементу столбца, десятому элементу строки");
                b100 = int.Parse(Console.ReadLine());
                a[9, 9] = b100;
            }
            if (n < 2) 
            {Console.WriteLine("Вы ввели мало вершин, поиск минимального оставного дерева невозможен");
            }
            if (n > 10)
            {
                Console.WriteLine("Вы ввели больше вершин, чем поддерживает данная программа");
                while (Console.ReadKey().Key != ConsoleKey.Enter) ;
            }
// на основе данных, введенных пользователем, строится матрица весов неориентированного // графа
            for (i = 0; i < n; i++)
            {
                used[i] = 0; 
                for (j = 0; j < n; j++)
                    a1[i, j] = 0;
            }
            used[0] = 1;
 // строится минимальное остовное дерево алгоритмом Прима: делается цикл, который           
// прерывается только тогда, когда все элементы массива станут снова равны 100000. В           
// первую очередь начиная с корневого элемента неориентированного графа здесь это             
// диагональ выше главной диагонали матрицы находится минимальный элемент массива. Он  
// запоминается в переменной min и ему присваивается 100000. Если ребро подходящее            
// минимальный элемент вычеркивается, а цикл начинается с начала. Подходящее ребро или  
// нет, проверяет массив из n элементов. Каждый элемент равен 1 или 0. Когда вершина           
// включается в дерево, в элемент массива с ее номером записывается 1 где изначально все         
// элементы массива, кроме первого равны 0. Если i – строка и j – столбец при выборе ребра    
// уже равны единице, то ребро не подходит для построения минимального остовного дерева. 
// Когда все i – строки j –столбцы равны единице, то алгоритм прекращает работу, так как все  
// вершины исходного неориентированного графа включены в новый граф. Также здесь          
// отмечается вес, строка и столбец включенного в новый граф ребра
            while (count < n - 1)
            {
                float min = 100000;
                for (i = 0; i < n; i++)
                {
                    if (used[i] != 0)
                    {
                        for (j = 0; j < n; j++)
                        {
                            if ((a[i, j] < min) && (a[i, j] != 0) && (used[j]) == 0)
                            {
                                Console.WriteLine(" " + "Строка и столбец найденного элемента " +"[" + a[i, 0] + " , " + a[0, j] + "]");
                                min = a[i, j];
                            }
                        }
                    }
                }
                Console.WriteLine("Вес безопасных ребер входящих в минимальное оставное дерево ");
                    for (int k = 0; k < n; k++)
                    {  
                        for (j = 0; j < n; j++)
                        {
                            if ((a[k, j] == min) && (used[j] == 0))
                            {
                                used[j] = 1;
                                a1[k, j] = a1[j, k] = min;
                                s1 = s1 + a1[j, k];
                                k = n;
                                count = count + 1;
                                Console.WriteLine(" " + min + " --> ");
                                break;  
                            }  
                        }
                        if (s1 == 0) Console.WriteLine("Найти минимальное остовное дерево невозможно");
                    }
                }
// суммируется вес ребер минимального остовного дерева и показывается вес минимального   
// остовного дерева составляющего сумму ребер этого дерева           
 for (i = 0; i < n; i++)
            {
                Console.WriteLine(" \n");
                for (j = 0; j < n; j++)
                    Console.Write(" "+a[i, j]);  // вес ребер входящих в минимальное дерево  
            }
            Console.WriteLine(" "+"Минимальный суммарный вес остовного дерева ="+s1);
            while (Console.ReadKey().Key != ConsoleKey.Enter);
        }      
    }
}
